Repository stackitcloud/gardener-extension-provider-openstack, pull requests merged in 2024-06, with the labels that each got.

#54 Fix linter error
  pkg/controller/infrastructure/configvalidator.go
Labels: size/XS, approved, lgtm

#56 Use args in Deployment
  VERSION
  charts/gardener-extension-provider-openstack/templates/deployment.yaml
  example/controller-registration.yaml
  pkg/controller/healthcheck/add.go
Labels: kind/enhancement, size/S, approved, lgtm

#57 Pass region to all openstack clients
  pkg/controller/bastion/actuator_delete.go
  pkg/controller/bastion/actuator_reconcile.go
  pkg/controller/dnsrecord/actuator.go
  pkg/controller/dnsrecord/actuator_test.go
  pkg/controller/infrastructure/actuator_delete.go
  pkg/controller/infrastructure/configvalidator.go
  pkg/controller/infrastructure/configvalidator_test.go
  pkg/controller/worker/machine_dependencies.go
  pkg/controller/worker/machine_dependencies_test.go
Labels: size/M, approved, kind/bug, lgtm
